name: Build and Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '15.1.0'

      - name: Install and Build
        run: |
          npm ci --only=production
          npm run build
        env:
          CI: false
          REACT_APP_FB_ID: ${{ secrets.FB_ID }}
          REACT_APP_FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
